# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

##############################################################################
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.


   config.vm.define "bot" do |bot|
      bot.vm.box = "bot"
        bot.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']
        aws.keypair_name = ENV['AWS_KEYNAME']


        aws.tags = {
            'Name' => 'Lecrin_Bot bot',
            'Environment' => 'vagrant-sandbox'
        } 

        aws.region = "eu-west-1"
        aws.ami = "ami-a192bad2"
        aws.instance_type = "t2.micro"
        aws.security_groups = ['AWS_SECURITY_GROUP_NAME'] #"vagrant"

        override.ssh.username = "ubuntu"  
        override.ssh.private_key_path = ENV['AWS_KEYPATH']
      end

      bot.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook-bot.yml"
        ansible.verbose = "v"
      end
   end

   config.vm.define "categorias" do |categorias|
      categorias.vm.box = "categorias"
        categorias.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']
        aws.keypair_name = ENV['AWS_KEYNAME']


        aws.tags = {
            'Name' => 'Lecrin_Bot categorias-noticias',
            'Environment' => 'vagrant-sandbox'
        } 

        aws.region = "eu-west-1"
        aws.ami = "ami-a192bad2"
        aws.instance_type = "t2.micro"
        aws.security_groups = ['AWS_SECURITY_GROUP_NAME']

        override.ssh.username = "ubuntu"  
        override.ssh.private_key_path = ENV['AWS_KEYPATH']
      end

      categorias.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook-categorias-noticias.yml"
        ansible.verbose = "v"
      end
   end
   
   config.vm.define "estadisticas" do |estadisticas|
      estadisticas.vm.box = "estadisticas"
        estadisticas.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']
        aws.keypair_name = ENV['AWS_KEYNAME']


        aws.tags = {
            'Name' => 'Lecrin_Bot estadisticas',
            'Environment' => 'vagrant-sandbox'
        } 

        aws.region = "eu-west-1"
        aws.ami = "ami-a192bad2"
        aws.instance_type = "t2.micro"
        aws.security_groups = ['AWS_SECURITY_GROUP_NAME']

        override.ssh.username = "ubuntu" 
        override.ssh.private_key_path = ENV['AWS_KEYPATH']
      end

      estadisticas.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook-estadisticas.yml"
        ansible.verbose = "v"
      end
   end

end
